# Generated by Django 4.1.1 on 2022-09-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PROCoast',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='PROPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
