# Generated by Django 4.1.1 on 2022-09-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_catparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesceiption',
            field=models.TextField(max_length=3000, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImage',
            field=models.ImageField(upload_to='category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
