# Generated by Django 4.1.1 on 2022-09-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_catparent_productalternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalternative',
            name='PROAlternative',
            field=models.ManyToManyField(related_name='alternative_products', to='product.product', verbose_name='Alternative'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROACProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessories_product', to='product.product', verbose_name='Product')),
                ('PROACcesseies', models.ManyToManyField(related_name='accessoris_products', to='product.product', verbose_name='Accessories')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
