# Generated by Django 4.1.1 on 2022-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_probrand_alter_product_procategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PROImg',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
