# Generated by Django 4.1.1 on 2022-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_options_product_proslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PROSlug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
    ]
