# Generated by Django 4.1.1 on 2022-09-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_proslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PROSlug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
