# Generated by Django 4.1.1 on 2022-09-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_proslug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='PROSlug',
        ),
    ]
