# Generated by Django 4.1.1 on 2022-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_slug_product_proslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRODiscountPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
    ]
