# Generated by Django 4.1.1 on 2022-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_prodiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PROISBestsaler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PROISNew',
            field=models.BooleanField(default=True),
        ),
    ]
