# Generated by Django 4.1.1 on 2022-09-22 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 21, 37, 28, 177563), verbose_name='join date '),
        ),
    ]
